# Generated by Django 3.2 on 2022-05-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_image_image_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
