# Generated by Django 3.2 on 2022-05-29 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_image_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.location'),
        ),
    ]
